### ISSUE TITLE
The voting mechanism selects the most consistent of the 20 results

### ISSUE THREAD

**Issue by huimoran** [bigbigwatermalon/C3SQL#12]
Hello. I saw in your paper that you said "After removing the errors from all the outcomes, we identify the most consistent SQL as the final SQL by applying a voting mechanism to these execution results." 

![20](https://github.com/bigbigwatermalon/C3SQL/assets/100472413/31f3feab-52c4-4654-b67d-e2403de33b22)
![30](https://github.com/bigbigwatermalon/C3SQL/assets/100472413/778b8ad2-067f-4556-b8d1-d4dd024136ce)

But what I see in your code is the choice of the first valid SQL query out of 20 generated for a natural language problem.

![code](https://github.com/bigbigwatermalon/C3SQL/assets/100472413/e7d3574c-306d-4a35-942a-1f542f0ab878)

Can you help me explain？

**Comment by bigbigwatermalon** [comment]
Hi, 

In line 200, we call the **_get_sqls_** function, which performs the self-consistency method to select the best SQL query from the candidate SQL queries. 
You could review the implementation of this function, as it should help you resolve any confusion.

**Comment by huimoran** [comment]
Ok, I see where you said, thank you for your answer.
