### ISSUE TITLE
关于utils.py

### ISSUE THREAD

**Issue by Z-Diviner** [bigbigwatermalon/C3SQL#13]
Hello, your paper has greatly inspired me, but could you please publish the code about utils.py?

**Comment by bigbigwatermalon** [comment]
Thanks for your attention. 

We initially used the Cross-Encoder model from RESDSQL to retrieve tables and columns, and the utils.py contains the relevant code. You can see the code in [RESDSQL](https://github.com/RUCKBReasoning/RESDSQL/blob/main/schema_item_classifier.py). 

Now, we exclusively rely on ChatGPT for retrieving schema items, so this code is no longer in use.
