### ISSUE TITLE
About the token cost

### ISSUE THREAD

**Issue by BeachWang** [bigbigwatermalon/C3SQL#2]
Hi, I have a question about the token cost of the prompt. 

There is a statement in your paper: "To address these issues, this paper proposes a novel ChatGPT-based zero-shot Text-to-SQL method, dubbed C3, which utilizes only approximately 1,000 tokens per query and achieves a better performance than fine-tuning-based methods." My question is that does the 1,000 tokens contain the cost of self-consistency. I find C3 applies self-consistency in table recall, column recall and final output. That require duplicate execution in my understanding.

Thank you.

**Comment by bigbigwatermalon** [comment]
Hi, Wang. Thanks for your attention to our work. 

In the statement "which utilizes only approximately 1,000 tokens per query", the token cost we statistic here is only the input tokens rather than input and completion tokens. The tokens counted on DIN-SQL are also the input tokens. 
I'm sorry we didn't explain clearly about this. We will fix the statement in the future version of the paper.

**Comment by BeachWang** [comment]
Thank you for your reply. But I still want to confirm that if the 1,000 tokens contain the cost of self-consistency. For example, for self-consistency, since we need 4 SQL queries to vote, we need to call the ChatGPT API 4 times to produce 4 results. Does it cost 250 input tokens in each calling? or 1000 input tokens in each calling?

**Comment by bigbigwatermalon** [comment]
> 
Hi Wang, 

Here we implement self-consistency by asking GPT API to reply **n** messages once. You just set the parameter **n** in the _openai.ChatCompletion.create_ function, and GPT will sample n replies to your instruction. 
![image](https://github.com/bigbigwatermalon/C3SQL/assets/45568047/d933be75-97c3-4ed2-b7de-4bb9ccb8af6d)

Therefore, the number of input tokens is always approximately 1000, cause we only need to call GPT API once.

**Comment by BeachWang** [comment]
I get it. Thank you very much!

**Comment by bigbigwatermalon** [comment]
> I get it. Thank you very much!

Okay, then I will close this issue. :)
