### ISSUE TITLE
db_contents in "preprocessed_data.json" is []

### ISSUE THREAD

**Issue by LeiShenVictoria** [bigbigwatermalon/C3SQL#4]
all "data_contents" in "preprocessed_data.json" after running "python src/preprocessing.py" are []

eg:

"db_contents": [
          [],
          [],
          [],
          [],
          [],
          [],
          []
        ]

**Comment by bigbigwatermalon** [comment]
Hi, thanks for your attention to our work. 
It is normal that most of the db_contents are empty, since db_contents are only used to contain the values that match the question in the database. 
BTW, you can search the keyword "volvo" to see whether the word in db_contents.

**Comment by LeiShenVictoria** [comment]
Oh, i see. Thanks for your fast reply!
