### ISSUE TITLE
Time required for execution?

### ISSUE THREAD

**Issue by horizon3902** [bigbigwatermalon/C3SQL#5]
Hello,

May I know what is the approximate time required to run your code? If you have the time required to execute each step too, (e.g.: - table recall step, column recall step, etc.), it would be really helpful.

Thank you

**Comment by XM-Dong** [comment]
Time taken for recalling table: approximately 7s per sample.
Time taken for recalling column: approximately 25s per sample.
Time taken for generating SQL: approximately 2s per sample.
The time spent also depends on the internet status and the rate limits of APl calls

**Comment by horizon3902** [comment]
Okay, noted. Thank you for your reply.

**Comment by horizon3902** [comment]
Okay, noted. Thank you for your reply.
