### ISSUE TITLE
CP prompt open

### ISSUE THREAD

**Issue by chuangchuang-wang** [bigbigwatermalon/C3SQL#7]
I think your work is great. I want to try to use the prompt after your CP (CH is not used for the time being) and feed it into my own large model (not chatgpt) to test the effect of CH. Can you open source the generated prompt?

**Comment by XM-Dong** [comment]
We use the MIT License, you can use our prompt with the preservation of copyright and license notices.

**Comment by chuangchuang-wang** [comment]
What I mean is where can I download the prompt you generated?

**Comment by XM-Dong** [comment]
You can find the generated files in #1 if you are unable to run our codes.

**Comment by chuangchuang-wang** [comment]
Thank you for your reply. I have another question. I saw that the schema part in the generated prompt is sorted according to the relevance to the problem, but the irrelevant schema is not deleted. The question I want to ask is how chatgpt knows the schemas we provide arranged by relevance to the problem? I didn't see this message when I entered the chatgpt prompt.
